### PR TITLE
Fix typos and formatting

### PR DESCRIPTION
**Pull request by iranzo**
Fix some typos and spell check in the docs as well as formatting.

### CODE REVIEW

**Comment by apinnick** [comment]
I have incorporated your typo fixes. I am not willing to add the tools in this PR.

**Comment by iranzo** [comment]
> I have incorporated your typo fixes. I am not willing to add the tools in this PR.

What tools are in this PR?

**Comment by apinnick** [comment]
> > I have incorporated your typo fixes. I am not willing to add the tools in this PR.
> 
> What tools are in this PR?

I saw .pre-commit-config.yaml and yaspeller.json. They look like config files for tools in your other PRs (contributor greeting, labelling issues, Dependabot). I am probably going to close those PRs as well because I do not want the burden of maintaining them.

**Comment by apinnick** [comment]
@iranzo I am reopening the PR. Can you please resolve the merge conflicts?

**Comment by iranzo** [comment]
Sure

**Comment by iranzo** [comment]
@apinnick already rebased

**Pull request merged**
