### PR TITLE
Migration environment considerations: new bullet point `OpenShift 4 Feature Gaps with OCP 3.11`

### PR DESCRIPTION
**Pull request by josgonza-rh**
I think it's key to consider if the __new environment__ offers you the same key features as your __current environment__.

There is a shared internal document where you can see all of those features gaps between the both OpenShift mayor versions [1].

An example of what I mean is the customizability of the OpenShift Ingress (routers): until OpenShift 4.5, something as common as let the client be able to send the routers access logs to his observability stack it was not possible. In some clients / cases this is a business impact as they have Government/Law requirements related to the management of the access logs.

[1] [OpenShift 4 Feature Gaps with OCP 3.11](https://docs.google.com/spreadsheets/d/1l5xb_kffXWMLIW5DSA2TckQHCGYB8Q-WOAeSh9TZsNw/edit#gid=0)

### CODE REVIEW

**Comment by apinnick** [comment]
@josgonza-rh Agree that the feature gaps should be mentioned. 

I will add a link to the downstream documentation: https://docs.openshift.com/container-platform/4.5/migration/migrating_3_4/planning-migration-3-to-4.html#planning-migration-3-to-4

This link explains the differences between OpenShift 3 and 4. It hasn't been updated for a while. Is there anything that should be added?

**Comment by josgonza-rh** [comment]
@apinnick 

>  It hasn't been updated for a while. Is there anything that should be added?

There are some missing things. Continuing with my previous example, the Ingress/Routers customizability:
- [RFE-730](https://issues.redhat.com/browse/RFE-730): ability to capture headers
- [RFE-720](https://issues.redhat.com/browse/RFE-720): for nbthread

But to keep the document generic context (the link you mention), at least I'd add `Ingress/Routers customizability` on it.
Maybe some other things could be added from the reviewing the document I mentioned in my first comment or the most popular RFEs (related to features on 3 not presents on 4).

**Comment by apinnick** [comment]
I see the bullet point you propose to add to the planning section. It duplicates the bullet I just added, with a link to the planning documentation and differences between OCP 3 and 4. If you check the master branch, you'll see the update.

Re: RFEs. RFE-730 is targeted for 4.6 and RFE-720 is targeted for 4.7. Are they available in the current release 4.5?

**Comment by josgonza-rh** [comment]
> Re: RFEs. RFE-730 is targeted for 4.6 and RFE-720 is targeted for 4.7. Are they available in the current release 4.5?

They are not available yet (on 4.5).

**Comment by apinnick** [comment]
Understood. I think I should close this PR since your proposed change is duplicated by my latest merge. Thanks

**Pull request closed without merging**
