### PR TITLE
Create website

### PR DESCRIPTION
**Pull request by iranzo**
imagen

This PR is built on top of 'spellcheck' one (#50)

It will push the rendered website to `gh-pages` branch and must be set accordingly in 'repository' options to use that branch for the rendered website

### CODE REVIEW

**Comment by mperezco** [comment]
If I understood correctly this, among other things, adds search capabilities to the published "website"

**Comment by iranzo** [comment]
It adds the search capabilities, also removes 'TOC' from the documents as it is shown directly on the side bar.

image

**Comment by mperezco** [comment]
Thanks for explaining @iranzo

**Comment by apinnick** [comment]
I did not merge PR#50. I am reluctant to add automated tools because of the maintenance overhead.

**Comment by ptrnull** [comment]
This is really useful, when is going to be merged?

**Comment by apinnick** [comment]
@iranzo Can you please resolve the merge conflicts?

**Comment by iranzo** [comment]
Sure

**Comment by iranzo** [comment]
@apinnick rebased

**Comment by apinnick** [comment]
@iranzo There are still conflicts, possibly from my merging PR#50. Would you mind rebasing? Thanks

**Comment by iranzo** [comment]
yup, let me rebase

**Comment by iranzo** [comment]
There youy go @apinnick

**Pull request merged**
