### PR TITLE
Update to include populating OCP4 with OCP3 images

### PR DESCRIPTION
**Pull request by dymurray**

### CODE REVIEW

**Review by jwmatthews — APPROVED** [review]

**Comment by jwmatthews** [comment]
@apinnick please advise how you'd like to handle this change, if we should merge as-is or if you'd like to suggest doc changes in the PR.

**Comment by apinnick** [comment]
> @apinnick please advise how you'd like to handle this change, if we should merge as-is or if you'd like to suggest doc changes in the PR.

There are too many changes for me to drop them into the PR. I recommend this be merged and then I will update it.

**Comment by apinnick** [comment]
@dymurray @jwmatthews  Do you want this included in downstream docs as well? If so, please create a Jira.

**Comment by jwmatthews** [comment]
Yes for downstream docs, let's track the request here: https://issues.redhat.com/browse/MIG-529

**Pull request merged**
