### PR TITLE
Add how to debug a PartialFailure and velero CLI tool

### PR DESCRIPTION
**Pull request by jwmatthews**
This is intended to introduce the 'velero' cli tool which is embedded in the Velero image we ship.  For deeper debugging into a failed migration this tool can help to provide information that is not apparent.  There are some issues that are not in the velero logs or Custom Resources and only available in data in the object storage.  The 'velero' cli tool consults the object store and displays the relevant information for the given Backup or Restore operation.

In addition, I wanted to give some more info about a PartialFailure and recommend for debugging a those the end user uses the velero tool to find the specifics of what went wrong.

### CODE REVIEW

**Comment by apinnick** [comment]
Starting review

**Comment by apinnick** [comment]
@jwmatthews  Do you want the Velero CLI tool and PartialFailure included in downstream docs?

**Comment by jwmatthews** [comment]
> @jwmatthews Do you want the Velero CLI tool and PartialFailure included in downstream docs?

Yes please.

Let's use https://issues.redhat.com/browse/MIG-527 to track the downstream inclusion

**Comment by apinnick** [comment]
I will merge this PR and then create a separate PR to improve the style and formatting.

**Pull request merged**
